# Generated by Django 5.1.1 on 2024-11-28 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.CharField(help_text="Unique tag name", max_length=50),
        ),
        migrations.AlterField(
            model_name="todo",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Timestamp of task creation (automatically set)",
            ),
        ),
        migrations.AlterField(
            model_name="todo",
            name="description",
            field=models.TextField(
                help_text="Detailed description of the task (max 1000 characters)",
                max_length=1000,
            ),
        ),
        migrations.AlterField(
            model_name="todo",
            name="due_date",
            field=models.DateTimeField(
                blank=True, help_text="Optional expected completion date", null=True
            ),
        ),
        migrations.AlterField(
            model_name="todo",
            name="status",
            field=models.CharField(
                choices=[
                    ("OPEN", "Open"),
                    ("WORKING", "Working"),
                    ("PENDING_REVIEW", "Pending Review"),
                    ("COMPLETED", "Completed"),
                    ("OVERDUE", "Overdue"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="OPEN",
                help_text="Current status of the task",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="todo",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                help_text="Optional tags associated with the task",
                to="core.tag",
            ),
        ),
        migrations.AlterField(
            model_name="todo",
            name="title",
            field=models.CharField(
                help_text="Title of the task (max 100 characters)", max_length=100
            ),
        ),
    ]
