# Generated by Django 5.1.1 on 2024-11-30 04:42

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_tag_name_alter_todo_created_at_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="tag",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("name"),
                name="unique_lowercase_tag_name",
            ),
        ),
    ]
