# Generated by Django 5.1.1 on 2024-11-30 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_tag_unique_lowercase_tag_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tag",
            options={},
        ),
    ]
