name: Django CI Workflow

# Trigger on every commit push and pull request
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# Define jobs
jobs:
  # Linting Job
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.11'
    
    - name: Install linting tools
      run: |
        python -m pip install --upgrade pip
        pip install flake8 black

    # Flake8 Linting
    - name: Lint with flake8
      run: |
        # Stop build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # Treat all errors as warnings
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    
    # Black Code Formatting Check
    - name: Check formatting with Black
      run: |
        black --check .

  # Testing Job
  test:
    needs: lint
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.11'
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-dev default-libmysqlclient-dev build-essential
    
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        working-directory: ./  # Specify the directory where manage.py is located
    # Run Unit Tests
    - name: Run Unit Tests
      run: |
        python manage.py test --verbosity 2
      working-directory: ./todolist  # Specify the directory where manage.py is located
    # Generate Coverage Report
    - name: Generate Coverage Report
      run: |
        pip install coverage
        coverage run --source='.' manage.py test
        coverage report
        coverage xml
    
    # Optional: Upload coverage to Codecov
    - name: Upload coverage
      uses: codecov/codecov-action@v3
      with:
        fail_ci_if_error: true
